Implementation of IGNORE_LIST_ENABLED Configuration Option
askrella/whatsapp-chatgpt pull request #262
Opened 2023-06-20 19:00 UTC by ClaytonCassi

Hello,

I've made some significant changes to the code that I'd like to share. In response to the application's need for an optional whitelist, I've added a new environmental variable called IGNORE_LIST_ENABLED.

With this new variable in place, it will provide us with the flexibility to decide whether to enable or disable the whitelist feature according to the application's needs.

This conditional validation for IGNORE_LIST_ENABLED is added to the .env file. If IGNORE_LIST_ENABLED is set to true, the application will validate the whitelist; if false or not defined, it will bypass the whitelist validation.

This addition provides increased configurability and can potentially streamline our processes depending on the circumstances.

You can find these updates in the attached commit. I've made sure to thoroughly test these changes, and everything seems to be functioning as expected. However, a second pair of eyes is always beneficial. Could you please review the modifications?

Please, let me know if you need any further information or clarification regarding these changes.

Thanks for your time and consideration.

Best Regards,

ClaytonCassi

2023-06-20 19:02 UTC, ClaytonCassi reviewed
remove comment

2023-06-29 14:18 UTC, steve-hb requested changes

2023-06-29 14:18 UTC, steve-hb commented on src/handlers/message.ts
> +		}
Can you fix the indentation?

2023-06-29 15:11 UTC, ClaytonCassi commented on src/handlers/message.ts
> +		}
Sure, its done!

2023-07-25 11:30 UTC, merged